server:
  port: 8801
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/Users/yanle/Desktop/9j.sqlite
    druid:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:C:/Users/yanle/Desktop/9j.sqlite
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/**/*Mapper.xml
forest:
  connect-timeout: 5000
  timeout: 5000
